pipeline {
    agent any
    tools {
        maven 'Maven3'
    }
    stages {
        stage('log version info') {
            steps {
                sh 'mvn --version'
                sh 'mvn clean install'
                }
            }
        }
    }
}
