pipeline {   
    agent any 
    tools {
        maven 'Maven3'
    }
    stages {
        stage('Build') {
            steps {
                dir('Backend') {
                    sh 'mvn clean install'
                }
            }
        }
        stage('SonarQube Analysis') {
            steps {
                dir('Backend') {
                    withSonarQubeEnv('SonarQubeServer') {
                        sh 'mvn sonar:sonar -Dsonar.projectKey=smartflow-backend'
                    }
                }
            }
        }
    }
}
