pipeline {
    agent any
    tools {
        maven 'Maven3'
    }
    stages {
        stage('Build') {
            steps {
                dir('Backend') {
                    sh 'mvn clean install'
                }
            }
        }
    }
}
